spring.application.name=EmployeeManagementAPI

#database configuration properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql-db:3306/techtezworkspace1
spring.datasource.username=root
spring.datasource.password=Admin

#hibernate specific configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.keepalive-time=10000

#server configurations
server.port=4040
server.servlet.context-path=/EmployeeManagementAPI






